[project]
name = "qbit-folder-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["python-qbittorrent>=0.4.3"]

[project.scripts]
sync = "main:main"

[tool.uv]
package = true
